name: past_questions
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  paystack_manager:
  rflutter_alert: ^2.0.2
  flutter_tex:


  # to handle SVGs for Android, iOS, and Web
  flutter_svg: ^0.21.0+1

  # state management, intelligent dependency injection, and route management
  get: ^4.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/tek.jpeg
    - assets/social13a1.png
    - assets/social13a2.png
    - assets/social12a1.png
    - assets/ghanaian.jpeg
    - assets/ict.jpeg
    - assets/math.png
    - assets/science.jpeg
    - assets/french.jpeg
    - assets/rme.jpeg
    - assets/english.jpeg
    - assets/social.jpeg
    - assets/export.json
    - assets/social10a.json
    - assets/social11a.json
    - assets/social12a.json
    - assets/social13a.json
    - assets/social14a.json
    - assets/social15a.json
    - assets/social16a.json
    - assets/social17a.json
    - assets/social18a.json
    - assets/social19a.json
    - assets/social20a.json
    - assets/social21a.json
    - assets/social10b.json
    - assets/social11b.json
    - assets/social12b.json
    - assets/social13b.json
    - assets/social14b.json
    - assets/social15b.json
    - assets/social16b.json
    - assets/social17b.json
    - assets/social18b.json
    - assets/social19b.json
    - assets/social20b.json
    - assets/social21b.json
    - assets/social21b.json
    - assets/ict10a.json
    - assets/ict11a.json
    - assets/ict12a.json
    - assets/ict13a.json
    - assets/ict14a.json
    - assets/ict15a.json
    - assets/ict16a.json
    - assets/ict17a.json
    - assets/ict18a.json
    - assets/ict19a.json
    - assets/ict20a.json
    - assets/ict21a.json
    - assets/ict10b.json
    - assets/ict11b.json
    - assets/ict12b.json
    - assets/ict13b.json
    - assets/ict14b.json
    - assets/ict15b.json
    - assets/ict16b.json
    - assets/ict17b.json
    - assets/ict18b.json
    - assets/ict19b.json
    - assets/ict20b.json
    - assets/ict21b.json
    - assets/rme10a.json
    - assets/rme11a.json
    - assets/rme12a.json
    - assets/rme13a.json
    - assets/rme14a.json
    - assets/rme15a.json
    - assets/rme16a.json
    - assets/rme17a.json
    - assets/rme18a.json
    - assets/rme19a.json
    - assets/rme20a.json
    - assets/rme21a.json
    - assets/rme10b.json
    - assets/rme11b.json
    - assets/rme12b.json
    - assets/rme13b.json
    - assets/rme14b.json
    - assets/rme15b.json
    - assets/rme16b.json
    - assets/rme17b.json
    - assets/rme18b.json
    - assets/rme19b.json
    - assets/rme20b.json
    - assets/rme21b.json
    - assets/twi10a.json
    - assets/twi11a.json
    - assets/twi12a.json
    - assets/twi13a.json
    - assets/twi14a.json
    - assets/twi15a.json
    - assets/twi16a.json
    - assets/twi17a.json
    - assets/twi18a.json
    - assets/twi19a.json
    - assets/twi20a.json
    - assets/twi21a.json
    - assets/twi10b.json
    - assets/twi11b.json
    - assets/twi12b.json
    - assets/twi13b.json
    - assets/twi14b.json
    - assets/twi15b.json
    - assets/twi16b.json
    - assets/twi17b.json
    - assets/twi18b.json
    - assets/twi19b.json
    - assets/twi20b.json
    - assets/twi21b.json
    - assets/english10a.json
    - assets/english11a.json
    - assets/english12a.json
    - assets/english13a.json
    - assets/english14a.json
    - assets/english15a.json
    - assets/english16a.json
    - assets/english17a.json
    - assets/english18a.json
    - assets/english19a.json
    - assets/english20a.json
    - assets/english21a.json
    - assets/english10b.json
    - assets/english11b.json
    - assets/english12b.json
    - assets/english13b.json
    - assets/english14b.json
    - assets/english15b.json
    - assets/english16b.json
    - assets/english17b.json
    - assets/english18b.json
    - assets/english19b.json
    - assets/english20b.json
    - assets/english21b.json
    - assets/science10a.json
    - assets/science11a.json
    - assets/science12a.json
    - assets/science13a.json
    - assets/science14a.json
    - assets/science15a.json
    - assets/science16a.json
    - assets/science17a.json
    - assets/science18a.json
    - assets/science19a.json
    - assets/science20a.json
    - assets/science21a.json
    - assets/science10b.json
    - assets/science11b.json
    - assets/science12b.json
    - assets/science13b.json
    - assets/science14b.json
    - assets/science15b.json
    - assets/science16b.json
    - assets/science17b.json
    - assets/science18b.json
    - assets/science19b.json
    - assets/science20b.json
    - assets/science21b.json
    - assets/french10a.json
    - assets/french11a.json
    - assets/french12a.json
    - assets/french13a.json
    - assets/french14a.json
    - assets/french15a.json
    - assets/french16a.json
    - assets/french17a.json
    - assets/french18a.json
    - assets/french19a.json
    - assets/french20a.json
    - assets/french21a.json
    - assets/french10b.json
    - assets/french11b.json
    - assets/french12b.json
    - assets/french13b.json
    - assets/french14b.json
    - assets/french15b.json
    - assets/french16b.json
    - assets/french17b.json
    - assets/french18b.json
    - assets/french19b.json
    - assets/french20b.json
    - assets/french21b.json
    - assets/bdt10a.json
    - assets/bdt11a.json
    - assets/bdt12a.json
    - assets/bdt13a.json
    - assets/bdt14a.json
    - assets/bdt15a.json
    - assets/bdt16a.json
    - assets/bdt17a.json
    - assets/bdt18a.json
    - assets/bdt19a.json
    - assets/bdt20a.json
    - assets/bdt21a.json
    - assets/bdt10b.json
    - assets/bdt11b.json
    - assets/bdt12b.json
    - assets/bdt13b.json
    - assets/bdt14b.json
    - assets/bdt15b.json
    - assets/bdt16b.json
    - assets/bdt17b.json
    - assets/bdt18b.json
    - assets/bdt19b.json
    - assets/bdt20b.json
    - assets/bdt21b.json
    - assets/math10a.json
    - assets/math11a.json
    - assets/math12a.json
    - assets/math13a.json
    - assets/math14a.json
    - assets/math15a.json
    - assets/math16a.json
    - assets/math17a.json
    - assets/math18a.json
    - assets/math19a.json
    - assets/math20a.json
    - assets/math21a.json
    - assets/math10b.json
    - assets/math11b.json
    - assets/math12b.json
    - assets/math13b.json
    - assets/math14b.json
    - assets/math15b.json
    - assets/math16b.json
    - assets/math17b.json
    - assets/math18b.json
    - assets/math19b.json
    - assets/math20b.json
    - assets/math21b.json
      
  


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
